/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.awt.Color;
import java.awt.GridLayout;
import static java.awt.image.ImageObserver.HEIGHT;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import defaultPackage.*;

/**
 *
 * @author Andrew
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    String username;
    String type;

    public Home() {
        initComponents();
        setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.WHITE);
        username = "";
        type = "";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        chooseCategory = new javax.swing.JComboBox<>();
        chooseGame = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        signUP = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        playGame = new javax.swing.JButton();
        createGame = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        exit = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        viewTeacherRequest = new javax.swing.JMenuItem();
        viewPendingGames = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/logo.png"))); // NOI18N

        jLabel7.setText("Choose Category");

        jLabel8.setText("Choose Game");

        chooseCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseCategoryActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Login");

        jLabel1.setText("Username");

        jLabel2.setText("Password");

        jLabel4.setText("Login As:");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Student");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Teacher");

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Admin");

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        signUP.setText("Sign Up");
        signUP.setAlignmentX(-1.0F);
        signUP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUPActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel5.setText("Don't have an Account ?");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel4))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel1)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jRadioButton3)
                                    .addComponent(jRadioButton2)
                                    .addComponent(jRadioButton1)
                                    .addComponent(jTextField1)
                                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(signUP, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(31, 31, 31))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(44, 44, 44))))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(25, 25, 25))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton3)
                .addGap(11, 11, 11)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(signUP)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator1)
        );

        playGame.setText("Play");
        playGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playGameActionPerformed(evt);
            }
        });

        createGame.setVisible(false);
        createGame.setText("Create Game");
        createGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createGameActionPerformed(evt);
            }
        });

        jMenu2.setText("File");

        jMenuItem3.setText("About");
        jMenuItem3.setPreferredSize(new java.awt.Dimension(150, 30));
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        exit.setText("Exit");
        exit.setPreferredSize(new java.awt.Dimension(150, 30));
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jMenu2.add(exit);

        jMenuBar1.add(jMenu2);

        jMenu1.setVisible(false);
        jMenu1.setText("View");
        jMenu1.setToolTipText("");

        viewTeacherRequest.setText("Teacher Requests");
        viewTeacherRequest.setPreferredSize(new java.awt.Dimension(150, 30));
        viewTeacherRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewTeacherRequestActionPerformed(evt);
            }
        });
        jMenu1.add(viewTeacherRequest);

        viewPendingGames.setText("Pending Games");
        viewPendingGames.setPreferredSize(new java.awt.Dimension(150, 30));
        viewPendingGames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPendingGamesActionPerformed(evt);
            }
        });
        jMenu1.add(viewPendingGames);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(chooseGame, 0, 181, Short.MAX_VALUE)
                            .addComponent(chooseCategory, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(createGame, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                            .addComponent(playGame, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(chooseCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(chooseGame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(playGame)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createGame)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (jRadioButton1.isSelected()) {
            if (StudentController.authenticate(jTextField1.getText(), String.valueOf(jPasswordField1.getPassword()))) {
                JOptionPane.showMessageDialog(null, "Welcome Back to ST-Comm !", "Welcome", JOptionPane.INFORMATION_MESSAGE);
                jPanel1.setVisible(false);
                int x = jPanel1.getWidth();
                this.remove(jPanel1);
                this.setSize(this.getWidth() - x, this.getHeight());
                this.setBounds(this.getX() + (x / 2), this.getY(), this.getWidth(), this.getHeight());
                username = jTextField1.getText();
                type = "Student";
            } else {
                JOptionPane.showMessageDialog(null, "Invalid Username/Password Combination !", "Error", JOptionPane.ERROR_MESSAGE);

            }
        } else if (jRadioButton2.isSelected()) {

            if (TeacherController.authenticate(jTextField1.getText(), String.valueOf(jPasswordField1.getPassword()))) {
                JOptionPane.showMessageDialog(null, "Welcome Back to ST-Comm !", "Welcome", JOptionPane.INFORMATION_MESSAGE);
                jPanel1.setVisible(false);
                int x = jPanel1.getWidth();
                this.remove(jPanel1);
                this.setSize(this.getWidth() - x, this.getHeight());
                createGame.setVisible(true);
                this.setBounds(this.getX() + (x / 2), this.getY(), this.getWidth(), this.getHeight());
                username = jTextField1.getText();

                type = "Teacher";

            } else {
                JOptionPane.showMessageDialog(null, "Invalid Username/Password Combination !", "Error", JOptionPane.ERROR_MESSAGE);

            }
        } else if (jRadioButton3.isSelected()) {
            if (RegistrantController.authenticate(jTextField1.getText(), String.valueOf(jPasswordField1.getPassword()))) {
                JOptionPane.showMessageDialog(null, "Welcome Back to ST-Comm !", "Welcome", JOptionPane.INFORMATION_MESSAGE);
                jPanel1.setVisible(false);
                jMenu1.setVisible(true);
                int x = jPanel1.getWidth();
                this.remove(jPanel1);
                this.setSize(this.getWidth() - x, this.getHeight());
                this.setBounds(this.getX() + (x / 2), this.getY(), this.getWidth(), this.getHeight());
                username = jTextField1.getText();
                type = "Admin";

            } else {
                JOptionPane.showMessageDialog(null, "Invalid Username/Password Combination !", "Error", JOptionPane.ERROR_MESSAGE);

            }
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        jMenu1.setVisible(false);
        createGame.setVisible(false);
        Vector<String> Categories = GameController.getCategories();
        for (int i = 0; i < Categories.size(); ++i) {
            chooseCategory.addItem(Categories.get(i));
        }


    }//GEN-LAST:event_formWindowOpened

    private void signUPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUPActionPerformed
        SignUpForm s = new SignUpForm();
        s.setVisible(true);
    }//GEN-LAST:event_signUPActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void chooseCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseCategoryActionPerformed
        chooseGame.removeAllItems();
        Vector<String> Games = GameController.getGames(chooseCategory.getSelectedItem().toString());
        for (int i = 0; i < Games.size(); ++i) {
            chooseGame.addItem(Games.get(i));
        }
    }//GEN-LAST:event_chooseCategoryActionPerformed

    private void viewPendingGamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPendingGamesActionPerformed
        PendingGames pg = new PendingGames();
        pg.setVisible(true);

    }//GEN-LAST:event_viewPendingGamesActionPerformed

    private void viewTeacherRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewTeacherRequestActionPerformed
        TeacherRequests tr = new TeacherRequests();
        tr.setVisible(true);
    }//GEN-LAST:event_viewTeacherRequestActionPerformed

    private void createGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createGameActionPerformed
        if (chooseCategory.getSelectedItem() != null) {
            GameTemplate gt = new GameTemplate();
            gt.setTeacherName(username);
            if (chooseCategory.getSelectedItem() != null) {
                gt.setCategoryName(chooseCategory.getSelectedItem().toString());
                gt.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "Please Choose Category !", "Error", JOptionPane.ERROR_MESSAGE);

            }
        }
    }//GEN-LAST:event_createGameActionPerformed

    private void playGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playGameActionPerformed
        if(chooseGame.getSelectedItem()==null){
            JOptionPane.showMessageDialog(null, "Please Choose Game !", "ST-Comm", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(chooseCategory.getSelectedItem()==null){
            JOptionPane.showMessageDialog(null, "Please Choose Category !", "ST-Comm", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (type.equals("Student")) {
            if (!GameController.isUnlocked(chooseGame.getSelectedItem().toString(), username)) {
                JOptionPane.showMessageDialog(null, "This Game is Locked As Your Level is Less than Game Level\n"
                        + "Play more games to increase your Level !", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        try {

            int score = GameController.playGame(chooseGame.getSelectedItem().toString());
            if (type.equals("Student")) {
                StudentController.saveScore(username, score, chooseGame.getSelectedItem().toString());
            }
            JOptionPane.showMessageDialog(null, "The Game Finished !\nYour Score is " + score, "ST-Comm", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.toString(), "ST-Comm", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_playGameActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        JOptionPane.showMessageDialog(null, "ST-Com ( Student/Teacher Community ) is a web application "
                + "\n that helps Students to learn a lot of things by playnig simple games.\n"
                + "Designed and Implemented By: AmbCamp Team\nAhmed Hussien\nAhmed Mohammed\nMariam Ashraf\nAndrew Emad", "ST-Comm", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    public static int displayQuestion(Question question, int numOfQuestions, int idx) {
        JLabel statement = new JLabel(question.getQuestionStatement());
        JPanel jp = new JPanel();
        jp.setLayout(new GridLayout(6, 5, 10, 10));
        jp.add(statement);
        if (question.getType() == QuestionType.TRUEorFALSE) {
            ButtonGroup bg = new ButtonGroup();
            JLabel a2 = new JLabel("");
            JRadioButton r1 = new JRadioButton("True");
            JRadioButton r2 = new JRadioButton("False");
            r1.setSelected(true);

            bg.add(r1);
            bg.add(r2);
            jp.add(r1);
            jp.add(r2);

            int result = JOptionPane.showConfirmDialog(null, jp,
                    "Question " + (idx + 1) + " Out Of " + numOfQuestions, JOptionPane.OK_CANCEL_OPTION);
            if (result != JOptionPane.OK_OPTION) {
                return -1;
            }
            int answer = 0;
            if (r1.isSelected()) {
                answer = 0;
            } else if (r2.isSelected()) {
                answer = 1;
            }
            JOptionPane.showMessageDialog(null, "Correct Answer is ' " + question.getChoices().get(question.getCorrectAnswer()) + " '", "ST-Comm", JOptionPane.INFORMATION_MESSAGE);

            return answer;
        } else {
            ButtonGroup bg = new ButtonGroup();
            JLabel a2 = new JLabel("");
            JRadioButton r1 = new JRadioButton(question.getChoices().get(0));
            JRadioButton r2 = new JRadioButton(question.getChoices().get(1));
            JRadioButton r3 = new JRadioButton(question.getChoices().get(2));
            JRadioButton r4 = new JRadioButton(question.getChoices().get(3));
            r1.setSelected(true);
            bg.add(r1);
            bg.add(r2);
            bg.add(r3);
            bg.add(r4);
            jp.add(r1);
            jp.add(r2);
            jp.add(r3);
            jp.add(r4);
            int result = JOptionPane.showConfirmDialog(null, jp,
                    "Question " + (idx + 1) + " Out Of " + numOfQuestions, JOptionPane.OK_CANCEL_OPTION);
            if (result != JOptionPane.OK_OPTION) {
                return -1;
            }
            int answer = 0;
            if (r1.isSelected()) {
                answer = 0;
            } else if (r2.isSelected()) {
                answer = 1;
            } else if (r3.isSelected()) {
                answer = 2;
            } else if (r4.isSelected()) {
                answer = 3;
            }
            JOptionPane.showMessageDialog(null, "Correct Answer is ' " + question.getChoices().get(question.getCorrectAnswer()) + " '", "ST-Comm", JOptionPane.INFORMATION_MESSAGE);

            return answer;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> chooseCategory;
    private javax.swing.JComboBox<String> chooseGame;
    private javax.swing.JButton createGame;
    private javax.swing.JMenuItem exit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton playGame;
    private javax.swing.JButton signUP;
    private javax.swing.JMenuItem viewPendingGames;
    private javax.swing.JMenuItem viewTeacherRequest;
    // End of variables declaration//GEN-END:variables
}
